name: bAnnouncer
main: mccloskey.callum.bannouncer.Main
version: 1.2.9
author: Callum McCloskey (Coltify)
description: Auto announcement with a messaging centering feature that outshines any other!
commands: 
  bannouncer:
   aliases: [ ba]
   description: Manage and control announcements easily.
  toggleannouncements:
   aliases: [ ta]
   description: Toggle announcements being sent to you.
 
