wname: bAnnouncer
main: mccloskey.callum.bannouncer.Main
version: 1.2.8
author: Callum McCloskey (Coltify)
description: Auto announcement with a messaging centering feature that outshines any other!
commands: 
  bannouncer:
   aliases: [ ba]
   description: Manage and control announcements easily.
 
